- src/finml_utils/dataframes.py
> fix(DataFrames): `concat_on_columns()` should always return a DataFrame

- .github/workflows/ruff.yaml
- pyproject.toml
- src/finml_utils/__init__.py
- src/finml_utils/parallel.py
> feature(Parallel): added `pmap` function

- src/finml_utils/dataframes.py
- src/finml_utils/list.py
> fix(Types): use input Sequences instead of lists to satisfy pyright

- src/finml_utils/dataframes.py
- tests/test_dataframes.py
> feature(Pandas): Rebase series to a given initial base.

- src/finml_utils/returns.py
> fix(Returns): only fill the first value of `to_returns()` with 0.0

- src/finml_utils/stats.py
> feature(Stats): `beta` function

- src/finml_utils/dataframes.py
> feature(DataFrames): added `remove_duplicate_columns()`

- src/finml_utils/returns.py
> feture(Returns): added optional `clip` argument

- src/finml_utils/returns.py
- tests/test_returns.py
> fix(Returns): apply clipping correctly in `to_log_returns()`

- pyproject.toml
- src/finml_utils/returns.py
- tests/test_returns.py
> fix(Returns): to_returns() should still accept a DataFrame

- src/finml_utils/parallel.py
> fix(Parallel): only create a pool if necessary

- src/finml_utils/s3_store.py
> fix(S3Store): silent option

- src/finml_utils/s3_store.py
> fix(S3Store): use a temporary file when downloading

- pyproject.toml
- src/finml_utils/__init__.py
- src/finml_utils/backtest.py
- src/finml_utils/dataframes.py
- src/finml_utils/decisiontree.py
- src/finml_utils/metrics.py
- src/finml_utils/parallel.py
- src/finml_utils/returns.py
- src/finml_utils/s3_store.py
- src/finml_utils/signal.py
- src/finml_utils/stats.py
- src/finml_utils/window.py
- tests/test_dataframes.py
- tests/test_decisiontree.py
- tests/test_stats.py
> feature(Backtesting): added various utils functions from another repository

- pyproject.toml
- src/finml_utils/__init__.py
- src/finml_utils/dataframes.py
- src/finml_utils/env.py
- src/finml_utils/obj.py
- src/finml_utils/path.py
> feature(Path): added `path`, `obj` and `env`  files

- src/finml_utils/transformations.py
> feature(Zscore): added optional `clip_lower` & `clip_upper` parameters

- src/finml_utils/transformations.py
> feature(Transformation): added `absolute` parameter to zscore

- src/finml_utils/decisiontree.py
> fix(DecisionTree): store all properties as native python types

- src/finml_utils/__init__.py
- src/finml_utils/jsonencodable.py
> feature(JSONEncodable): added new class & functions

- pyproject.toml
> fix(Dependencies): pin dependencies to minor version

- src/finml_utils/__init__.py
- src/finml_utils/columns.py
- src/finml_utils/dict.py
- src/finml_utils/forward.py
- src/finml_utils/splitters.py
> feature(Columns): added columns, forward, splitters from fold

- tests/generate.py
- tests/test_forward.py
- tests/test_splitters.py
> feature(Tests): added tests for create_forward_rolling & splitters

- src/finml_utils/s3_store.py
> feature(RemoteStore): Upload dataframe, read folder as dataframe

- src/finml_utils/decisiontree.py
> fix(Model): support `num_trees` up to 9

- src/finml_utils/decisiontree.py
> fix(Model): support `threshold_margin` == 0

- src/finml_utils/s3_store.py
…ify temp folder and wget and file move os.system() commands accordingly
> fix(S3Store): add Windows compatibility
